vmec_file: wout_vmec.nc

invessel_build:
  toroidal_angles: [0.0, 11.25, 22.5, 33.75, 45.0, 56.25, 67.5, 78.75, 90.0]
  poloidal_angles: [0.0, 45.0, 90.0, 135.0, 180.0, 225.0, 270.0, 315.0, 360.0]
  wall_s: 1.08
  radial_build:
    first_wall:
      thickness_matrix:
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
    breeder:
      thickness_matrix:
        - [75, 75, 75, 25, 25, 25, 75, 75, 75]
        - [75, 75, 75, 25, 25, 75, 75, 75, 75]
        - [75, 75, 25, 25, 75, 75, 75, 75, 75]
        - [65, 25, 25, 65, 75, 75, 75, 75, 65]
        - [45, 45, 75, 75, 75, 75, 75, 45, 45]
        - [65, 75, 75, 75, 75, 65, 25, 25, 65]
        - [75, 75, 75, 75, 75, 25, 25, 75, 75]
        - [75, 75, 75, 75, 25, 25, 75, 75, 75]
        - [75, 75, 75, 25, 25, 25, 75, 75, 75]
    back_wall:
      thickness_matrix:
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
        - [5, 5, 5, 5, 5, 5, 5, 5, 5]
    shield:
      thickness_matrix:
        - [50, 50, 50, 50, 50, 50, 50, 50, 50]
        - [50, 50, 50, 50, 50, 50, 50, 50, 50]
        - [50, 50, 50, 50, 50, 50, 50, 50, 50]
        - [50, 50, 50, 50, 50, 50, 50, 50, 50]
        - [50, 50, 50, 50, 50, 50, 50, 50, 50]
        - [50, 50, 50, 50, 50, 50, 50, 50, 50]
        - [50, 50, 50, 50, 50, 50, 50, 50, 50]
        - [50, 50, 50, 50, 50, 50, 50, 50, 50]
        - [50, 50, 50, 50, 50, 50, 50, 50, 50]
    vacuum_vessel:
      thickness_matrix:
        - [10, 10, 10, 10, 10, 10, 10, 10, 10]
        - [10, 10, 10, 10, 10, 10, 10, 10, 10]
        - [10, 10, 10, 10, 10, 10, 10, 10, 10]
        - [10, 10, 10, 10, 10, 10, 10, 10, 10]
        - [10, 10, 10, 10, 10, 10, 10, 10, 10]
        - [10, 10, 10, 10, 10, 10, 10, 10, 10]
        - [10, 10, 10, 10, 10, 10, 10, 10, 10]
        - [10, 10, 10, 10, 10, 10, 10, 10, 10]
        - [10, 10, 10, 10, 10, 10, 10, 10, 10]
      mat_tag: vac_vessel
  plasma_mat_tag: Vacuum
  sol_mat_tag: Vacuum
  export_cad_to_dagmc: False

magnet_coils:
  coils_file: coils.example
  cross_section: [circle, 20.0]
  toroidal_extent: 90.0
  sample_mod: 6
  step_filename: magnet_coils
  export_mesh: True
  mesh_filename: magnet_mesh

source_mesh:
  mesh_size: [11, 81, 61]
  toroidal_extent: 90.0
  filename: source_mesh

dagmc_export:
  skip_imprint: False
  legacy_faceting: True
  filename: dagmc
